version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  ahoy:
    image: ahoy:latest
    environment:
      - REDIS_HOST=redis://redis:6379
      - PORT=4444
    ports:
      - 4444:4444
